run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  govet:
    check-shadowing: false
  errcheck:
    check-type-assertions: false
    check-blank: false
